### ISSUE TITLE
Example for the worker/complete node

### ISSUE THREAD

**Issue by gizmo84** [pedesen/node-red-contrib-zeebe#15]
Hi there,

I just tried to implement a zeebe worker over node-red:

- added a worker node to my flow (listening to "echo" tasks)
- connected the output to a debug node
- connected the output to a complete node

The output of the debug node:

{"payload":{"job":{"key":"2251799813769806","type":"echo","workflowInstanceKey":"2251799813769794","bpmnProcessId":"ECHO","workflowDefinitionVersion":1,"workflowKey":"2251799813728423","elementId":"ServiceTask_0phglip","elementInstanceKey":"2251799813769803","customHeaders":{},"worker":"08adfae5-82b8-4e27-bd53-325282bc9958","retries":3,"deadline":"1569336118974","variables":{}},"complete":{}},"_msgid":"cbe132e.57828d"}

The complete node keep saying: "complete is not a function"

So I tried several tricks to set complete to a function but I'm failing. Can someone explain how to set complete to a function so the job is successfully completed in zeebe ? I just want to output variables at first.

Perhaps it can be helpful to document some examples in the README ?

**Comment by pedesen** [comment]
Hey,

if the worker is directly connected to a complete node, it should just work. I'll investigate what's going on, because it seems to be a bug. Thanks for reporting!

**Comment by pedesen** [comment]
@gizmo84 It's fixed! Please update to node-red-contrib-zeebe 0.5.1 and let me know, if you have any more issues. It should work now like you tried.

The problem was: In the complete node I wall calling `complete()`, but that got removed from zeebe-client-node-js v. 0.20.6 (see here: https://github.com/creditsenseau/zeebe-client-node-js/releases/tag/v0.20.6). So I need to call `complete.success()` now.

**Comment by pedesen** [comment]
@gizmo84 Issue closed. Feel free to reopen, if you still have issues...

**Comment by gizmo84** [comment]
Thanks for the fix, it works :)
